# Generated by Django 4.0 on 2022-01-23 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='test',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
