# Generated by Django 4.0 on 2022-01-23 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_post_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='test',
        ),
    ]
